dependencies:
- name: zookeeper
  version: 1.3.0
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: zookeeper.enabled
- name: mysql
  version: 0.10.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
- name: postgresql
  version: 4.0.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
